stages:
  - build
  - deploy

variables:
  # Wyłączamy certyfikaty dla Dockera
  DOCKER_TLS_CERTDIR: ""
  # Dane Twojego serwera produkcyjnego
  APP_SERVER_IP: "192.168.88.105"
  APP_USER: "msr"

build-image:
  stage: build
  image: docker:latest
  # --- KLUCZOWA ZMIANA ---
  # Wymuszamy MTU 1300 wewnątrz Runnera
  services:
    - name: docker:dind
      command: ["--mtu=1300"]
  # -----------------------
  script:
    - echo "Budowanie obrazu..."
    # Dodajemy --network=host dla pewności
    - docker build --network=host -t python-app:latest .
    - docker save -o python-app.tar python-app:latest
  artifacts:
    paths:
      - python-app.tar
    expire_in: 1 hour

deploy-job:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - echo "Wysyłanie na App-Server ($APP_SERVER_IP)..."
    - scp python-app.tar $APP_USER@$APP_SERVER_IP:/home/$APP_USER/
    
    - echo "Uruchamianie na App-Serverze..."
    - ssh $APP_USER@$APP_SERVER_IP "docker stop python-app || true"
    - ssh $APP_USER@$APP_SERVER_IP "docker rm python-app || true"
    - ssh $APP_USER@$APP_SERVER_IP "docker load -i /home/$APP_USER/python-app.tar"
    - ssh $APP_USER@$APP_SERVER_IP "docker run -d -p 8080:8080 --name python-app python-app:latest"
