stages:
  - build
  - deploy

variables:
  DOCKER_HOST: unix:///var/run/docker.sock
  APP_SERVER_IP: "192.168.0.114"
  APP_USER: "msr"

build-image:
  stage: build
  image: docker:latest
  script:
    - echo "Budowanie obrazu przy użyciu głównego demona Dockera..."
    - docker build --network=host -t python-app:latest .
    - docker save -o python-app.tar python-app:latest
  artifacts:
    paths:
      - python-app.tar
    expire_in: 1 hour

deploy-job:
  stage: deploy
  image: kroniak/ssh-client:latest
  before_script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
  script:
    - echo "Wdrażanie aplikacji, bazy Redis i serwera NGINX (SSL)..."
    - mkdir -p nginx/ssl
    - echo "$SSL_CERTIFICATE" > nginx/ssl/app.crt
    - echo "$SSL_PRIVATE_KEY" > nginx/ssl/app.key
    - scp -r nginx/ $APP_USER@$APP_SERVER_IP:/home/$APP_USER/
    - scp -o StrictHostKeyChecking=no python-app.tar $APP_USER@$APP_SERVER_IP:/home/$APP_USER/
    - ssh -o StrictHostKeyChecking=no $APP_USER@$APP_SERVER_IP "docker load -i /home/$APP_USER/python-app.tar"
    - ssh -o StrictHostKeyChecking=no $APP_USER@$APP_SERVER_IP "docker rm -f python-app redis nginx || true"
    - ssh -o StrictHostKeyChecking=no $APP_USER@$APP_SERVER_IP "docker network create app-network || true"
    - ssh -o StrictHostKeyChecking=no $APP_USER@$APP_SERVER_IP "docker run -d --name redis --network app-network -v redis_data:/data --restart always redis:latest redis-server --appendonly yes"
    - ssh -o StrictHostKeyChecking=no $APP_USER@$APP_SERVER_IP "docker run -d --name python-app --network app-network --restart always python-app:latest"
    - ssh -o StrictHostKeyChecking=no $APP_USER@$APP_SERVER_IP "docker run -d --name nginx --network app-network -p 80:80 -p 443:443 -v /home/$APP_USER/nginx/default.conf:/etc/nginx/conf.d/default.conf -v /home/$APP_USER/nginx/ssl:/etc/nginx/ssl --restart always nginx:latest"
    